# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'skip ci')"

    steps:
      - uses: actions/checkout@v2
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: 'Use Node.js ${{ steps.nvm.outputs.NVMRC }}'
        uses: actions/setup-node@v1
        with:
          node-version: '${{ steps.nvm.outputs.NVMRC }}'
      - run: npm ci
      - run: npm test
      - run: npm run build
      - name: Add & Commit
        uses: EndBug/add-and-commit@v4.4.0 # You can change this to use a specific version
        with:
          add: data
          author_name: tsboter
          author_email: roboter@tsb-berlin.de
          message: 'Update data/** via workflow'
        env:
          # This is necessary in order to push a commit to the repo
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
          # Runs a set of commands using the runners shell
